# Putting this file into packages/ because VSCode Rust extension
# only searches 1 level for Cargofiles

[package]
name = "remotion-renderer"
version = "0.1.0"
authors = ["Jonny Burger <jonny@remotion.dev>"]
edition = "2021"

[dependencies]
png = "0.17.7"
serde = {version =  "1.0.151", features = ["derive"]}
serde_json = "1.0.89"
jpeg-decoder = "0.3"
jpeg-encoder = "0.5.1"
lazy_static = "1.4"
rayon = "1.7.0"
image = "0.23.7"
arboard = "3.2.0"
sysinfo = "0.29.9"
mp4 = {git = "https://github.com/jonnyburger/mp4-rust", rev = "92ba375738cc2f05a4d754e1f968cf2e97d06641"}
ffmpeg-next = {git = "https://github.com/remotion-dev/rust-ffmpeg", rev ="e09ec7f3bc2898beb9fecaf740088dbc0732fd00"}

[[bin]]
name = "remotion"
path = "renderer/rust/main.rs"

