on:
  push:
    branches:
      - main
  pull_request:
name: Install and Test

env:
  FORCE_COLOR: 1
jobs:
  lambda-tests:
    runs-on: ubuntu-latest
    name: Lambda integration
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: |
          corepack enable
      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "PNPM_STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.PNPM_STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: "packages/renderer -> target"
      - name: Install
        run: pnpm install --frozen-lockfile
      - name: Build cache
        uses: actions/cache@v3.0.11
        with:
          # Currently disabled but would love to enable:
          # packages/*/dist
          # packages/*/tsconfig.tsbuildinfo
          path: |
            packages/*/.turbo
            node_modules/.cache
          key: ts-${{ runner.os }}-node16-v3
      - name: build
        run: |
          pnpm build
      - name: Test Lambda IT
        run: |
          cd packages/it-tests && pnpm run testlambda
      - name: Test Lambda E2E
        run: |
          cd packages/lambda && pnpm run testintegration
  ssr-tests:
    runs-on: ubuntu-latest
    name: SSR integration
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: |
          corepack enable
      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "PNPM_STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.PNPM_STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - name: Install
        run: pnpm install --frozen-lockfile
      - name: Build cache
        uses: actions/cache@v3.0.11
        with:
          # Disbled but would like to enable:
          # packages/*/dist
          # packages/*/tsconfig.tsbuildinfo
          path: |
            packages/*/.turbo
            node_modules/.cache
          key: ts-${{ runner.os }}-node16-v3
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: "packages/renderer -> target"
      - name: build
        run: |
          pnpm build
      - name: Test SSR
        timeout-minutes: 5
        run: |
          cd packages/it-tests && pnpm run testssr
  lint:
    runs-on: ubuntu-latest
    name: Linting + Formatting
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: |
          corepack enable
      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "PNPM_STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.PNPM_STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - name: Install
        run: pnpm install --frozen-lockfile
      - name: Perform stylecheck
        timeout-minutes: 5
        run: |
          pnpm run stylecheck
  build:
    name: Build Node ${{ matrix.node_version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            node_version: 16
          - os: windows-latest
            node_version: 16
          - os: macos-latest
            node_version: 16
          - os: ubuntu-latest
            node_version: 20
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
      - name: Setup PHP with PHPUnit
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          tools: phpunit:10.1.3
      - run: |
          corepack enable
      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "PNPM_STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.PNPM_STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Cache node_modules/.cache
        uses: actions/cache@v3.0.11
        with:
          path: node_modules/.cache
          key: deps-${{ runner.os }}-node${{ matrix.node_version }}-v3
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: "packages/renderer -> target"
      - name: Install
        run: pnpm install --frozen-lockfile
      - name: Build cache
        uses: actions/cache@v3.0.11
        with:
          # Disabled but would love to enable:
          # packages/*/dist
          # packages/*/tsconfig.tsbuildinfo
          path: |
            packages/*/.turbo
            node_modules/.cache
          key: ts-${{ runner.os }}-node${{ matrix.node_version }}-v3

      - name: Build & Test
        run: |
          pnpm run ci
